version: 2

sources: 
  - name: etl_airbyte_raw
    database: world_football_data
    schema: etl_airbyte_raw
    tables:
      - name: appearances
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 96, period: hour}
      - name: club_games
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 96, period: hour}
      - name: clubs
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 96, period: hour}
      - name: competitions
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 96, period: hour}
      - name: games
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 96, period: hour}
      - name: player_valuations
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 96, period: hour}
      - name: players
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 48, period: hour}
          error_after: {count: 96, period: hour}
      
