version: 2

sources: 
  - name: etl_airbyte_
    database: world_football_data
    schema: etl_airbyte_
    tables:
      - name: appearances
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: club_games
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: clubs
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: competitions
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: games
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: player_valuations
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      - name: players
        loaded_at_field: _airbyte_emitted_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
      
